version: 2

# Build PDF & ePub
formats:
  - epub
  - pdf

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

python:
  install:
    - requirements: ./docs/requirements.txt